### ISSUE TITLE
Test fails on Windows 8.x Strawberry Perl 5.18.2 (64bit)

### ISSUE THREAD

**Issue by McA** [petdance/html-tidy#11]
Hi,

I tried to install the latest version (HTML-Tidy-1.56.tar) on Windows 8.0 64bit with Strawberry Perl 5.18.2.
The test 'unicode-nbsp.t' fails due to the fact that the string returned is NOT "&nbsp;\n" but "&nbsp;\r\n" under Windows.

Regards
McA

**Comment by soonix** [comment]
AFAICT the reason for this is, that Perl converts between "\n" and "\r\n" on I/O only, so that internally, all line endings are "\n", on any operating systems.
OTOH, tidyp, as a C program, relies on the C runtime, which doesn't provide this functionality, so it has to handle this internally.
The simplest solution, as you probably don't want to change tidyp's behaviour, is to reflect different behaviour in the test, appending not a simple "\n", but, depending on OS, "\n", "\r", or "\r\n" ...

**Comment by petdance** [comment]
Fixed with f4ff587
