### ISSUE TITLE
Does not support new tidy that supports html5 validation

### ISSUE THREAD

**Issue by jacksonofalltrades** [petdance/html-tidy#25]
Any plans to do so?

**Comment by petdance** [comment]
Point me to it.  Last I've known, there was no tidy that handled Perl 5 that was ready for prime time.

**Comment by geoffmcl** [comment]
@petdance sorry to be a little late to this party ;=))

But I think [HTML Tidy](https://github.com/htacg/tidy-html5/tree/master) - aka Release verion [5.4.0](https://github.com/htacg/tidy-html5/releases/tag/5.4.0) - **is** ready ;=))

As you can see Tidy is again very **actively** maintained, and the [next](https://github.com/htacg/tidy-html5) branch continues to grow and be stable... with issues being addressed and closed...

We have had some success in getting Tidy 5.2.0 into Debian distribution, and hope that will be upgraded to 5.4.0 soon, as in some other distributions, like [OpenSUSE](https://build.opensuse.org/package/show/openSUSE:Factory/tidy), and others...

While there have been a few changes in the header names, like `buffio.h` became `tidybuffio.h`, etc, the API remains essentially unchanged... and `tidyLibraryVersion()` is preferred to `tidyReleaseDate()`, but both are there... and we have moved to a CMake cross-port unix/Widnows/MAC building...

You **have** been very active in HTML Tidy's history, and hope you will again find some time to participate...

Since I am very interested in building HTML::Tidy for Perl v5.14.2, x64, for Windows, would help in any way I can... hopefully just using my `installed` say 5.5.24 libTidy... Tidy.dll/lib or Tidys.lib... thanks...

**Comment by petdance** [comment]
That's great news.  I'll try to look into it this week.

**Comment by petdance** [comment]
I'm so glad you're making actual releases.  Maybe I can get rid of tidyp.com.

**Comment by geoffmcl** [comment]
@petdance really thank you for the **quick** reply...

Yes, I agree, there should be no need for `tidyp.com`... the current `libTidy` is marching forward, very  **strongly**... and should be the basis for a `HTML::Tidy` **new** release...

It becomes how to first modify [Tidy.xs](https://github.com/petdance/html-tidy/blob/master/Tidy.xs) to the new header names... it seems not much other than the header name need be changed, **and** then how they are `found`...

In my Windows case installed `tidy` can be found in `F:\Projects\software.x64`, both the `bin\tidy.dll` or the static library, `lib\tidys.lib`, which I would prefer... and the required Tidy includes in `F:\Projects\software.x64\include`...

So with your help, I think this can be **easily** managed, updated... thanks...

**Comment by geoffmcl** [comment]
@petdance is this regard have opened a Tidy [issue](https://github.com/htacg/tidy-html5/issues/562) to address this... thanks...

**Comment by mrenvoize** [comment]
I'm really looking forward to this one too :+1:

**Comment by geoffmcl** [comment]
@petdance just an update...

Since we recently released **Tidy** 5.6.0, I opened an [Issue 3](https://github.com/geoffmcl/html-tidy/issues/3) to updated my `fork` to use the latest **Tidy** 5.7.3...

This time I did it in **both** Windows and Linux, and eventually got a good build, test and install of my `HTML::Tidy` version 5.61, in all systems tried... I am happy with the results... but...

It would be most appreciated if you, or others, could clone and test my [fork](https://github.com/geoffmcl/html-tidy), which now **defaults** to the `next` branch... thanks...

And if you are interested in my changes, I could create a PR... I have strongly undated the `README.markdown` to remove both `Alien::Tidyp` and `Tidyp`... and only use **Tidy** source 100% - the shared library in linux but the static library in Windows, for the reason given...

As always thank you for this great wrapper...

**Comment by petdance** [comment]
I really want to take the time to make a new HTML::Tidy that works with the new Tidy.  There are so many features I want to take advantage of, and HTML::Lint is just so long in the tooth. :-(

**Comment by geoffmcl** [comment]
@petdance,

> make a new HTML::Tidy that works with the new Tidy

That would be great, and that is what I tried to do in my [fork](https://github.com/geoffmcl/html-tidy)...

**Comment by petdance** [comment]
I've started today on my conversion of HTML::Tidy to use the new html-tidy 5.x version.

**Comment by petdance** [comment]
This work to use the new libtidy is now at https://github.com/petdance/html-tidy5.  This project will stay on the old version of libtidy.
