### ISSUE TITLE
clean.t fails

### ISSUE THREAD

**Issue by chorny** [petdance/html-tidy#26]
```
1..3
ok 1 - An object of class 'HTML::Tidy' isa 'HTML::Tidy'
ok 2 - clean() croaks when not given a string or list of strings
not ok 3 - $tidy->clean("") returns empty HTML document
#   Failed test '$tidy->clean("") returns empty HTML document'
#   at t/clean.t line 20.
#          got: '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2//EN">

# <html>

# <head>

# <meta name="generator" content="tidyp for Windows (v1.04), see www.w3.org">

# <title></title>

# </head>

# <body>

# </body>

# </html>

# '
#     expected: '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2//EN">
# <html>
# <head>
# <meta name="generator" content="tidyp for Linux (v1.02), see www.w3.org">
# <title></title>
# </head>
# <body>
# </body>
# </html>
# '
# Looks like you failed 1 test of 3.
```

**Comment by pghmcfc** [comment]
So it could only pass on Linux with tidyp version 1.02 (which is not the latest).

**Comment by geoffmcl** [comment]
@chorny it may pass if you applied the following patches...

Add options into the new()...

```
my $args = { newline => 'Lf',
    tidy_mark => 0 };
my $tidy = HTML::Tidy->new( $args );
```

And then remove `<meta name="generator" content="tidyp for Linux (v1.02), see www.w3.org">` line, from the _expected_empty_html...

Since you're in windows, tidy will add a `CRLF`, hence the line split in `got:`... this is usually fixed by forcing tidy to only use a `Lf`, hence the option `newline => 'Lf'`...

And since the name of the `generator` changes with OS and version, remove it, and ask tidy to **not** add this, with the option `tidy_mark => 0`... otherwise as @pghmcfc points out, this will only work in Linux, with 1.02...

HTH

PS: I am working on an updated `HTML::Tidy`, which uses the current [Tidy](https://github.com/htacg/tidy-html5) library in place of `tidyp`, and I just applied this [patch](https://github.com/geoffmcl/html-tidy/commit/18586374493c5256925ba953f221e76d33368296) to `clean.t`, and it works for me... warning, this is a **WIP**...

But if you are in Windows, and can build and install HTML Tidy, then maybe you can assist in testing my [fork](https://github.com/geoffmcl/html-tidy) of this repo, in `test1` branch... thanks... else you will have to wait until it is all finished, and if acceptable to @petdance, merged back into here, and released... who knows when that will be...

**Comment by shlomif** [comment]
Hi!

It fails here as well (x86-64 linux) - there are many CPAN Testers test failures with the version in CPAN - please fix it.

**Comment by geoffmcl** [comment]
@shlomif as mentioned above, I have addressed this issue, and others, in my **fork** -  https://github.com/geoffmcl/html-tidy, in the **test2** branch... now complete...

Of course, if you want to build it using the **latest** tidy, version 5.5.31 at time of writing, then you also need to clone, build and install the `next` branch of tidy - https://github.com/htacg/tidy-html5

Of course, if you have previously installed, used `tidyp`, `Alien::Tidyp`, then this needs to be removed first... the process still searches for this first...

The full process would be - build and install latest tidy -

```
# clone tidy, if not done
$ git clone git@github.com:htacg/tidy-html5.git
# or update, if done previously
$ cd tidy-html5
$ git pull
# build tidy - there is a 'build-me.sh' to do this...
$ cd build/cmake
$ cmake ../.. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release
$ make
# install latest tidy
$ sudo make install
# test tidy got installed
$ tidy -v
HTML Tidy for Linux version 5.5.31
```

Then clone my petdance fork - build, test, and install -

```
# clone my petdance html tidy fork -
$ git clone git@github.com:geoffmcl/html-tidy.git html-tidy-fork
$ cd html-tidy-fork     # get into source directory
$ git checkout test2    # get into correct `branch` **IMPORTANT**
$ ./build-me.sh         # use the provided shell script
# or you can do the steps manually
$ perl -f Makefile.PL
$ make
$ make test
```

There might remain an `Unknown error type: FAKE_ERROR_TYPE...` output, but is should PASS 100%...

If all is good, then `$ sudo make install` should finish the process...

If not, if you file an [issue](https://github.com/geoffmcl/html-tidy/issues) on my fork, I may be able to fix it...

Enjoy...

**Comment by shlomif** [comment]
Now it causes my Travis-CI builds to fail - https://travis-ci.org/shlomif/perl-begin/builds/251088700?utm_source=email&utm_medium=notification - please fix it on CPAN. @geoffmcl : as much as I appreciate your efforts, note that the point of this bug is to fix HTML::Tidy's installation using cpan clients, without having to resort to a more complicated build process.

**Comment by mstarnes** [comment]
cpan> install HTML::HTMLDoc is broken because of this.

**Comment by shlomif** [comment]
@petdance : hi! Is there any way I can help you with fixing this bug? Do you need anything? Ping!

**Comment by petdance** [comment]
@shlomif Have you tested the patch above?

**Comment by shlomif** [comment]
@petdance: I tested the #27 pull-req now - thanks!

**Comment by petdance** [comment]
This has been fixed.  I've uploaded 1.60 to PAUSE.

**Comment by shlomif** [comment]
On Wed, 13 Sep 2017 15:40:34 +0000 (UTC)
Andy Lester <notifications@github.com> wrote:

> This has been fixed.  I've uploaded 1.60 to PAUSE.
> 

Fabulous! Thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://is.gd/KNvczZ - The FSF Announces New Versions of the GPL

Monologue: one person talking to himself.
Dialogue: two persons talking to themselves.
    — Shaike Ophir: http://www.youtube.com/watch?v=2bpVrKm9QCc

Please reply to list if it's a mailing list post - http://shlom.in/reply .
